# Generated by Django 3.0.2 on 2020-02-18 06:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0003_auto_20200127_0331'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountM',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('AccountDescription', models.CharField(max_length=200)),
                ('AccountNumber', models.IntegerField(default=0)),
                ('AccountCategory', models.CharField(max_length=60)),
                ('AccountSubCategory', models.CharField(max_length=60)),
                ('AccountInitBalance', models.CharField(max_length=60)),
                ('AccountCredit', models.CharField(max_length=60)),
                ('AccountBalance', models.CharField(max_length=60)),
                ('Order', models.CharField(max_length=60)),
                ('Statements', models.FileField(upload_to='StatementsFile')),
                ('Comments', models.CharField(max_length=60)),
                ('DateAdded', models.DateField(auto_now=True)),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
