# Generated by Django 3.0.2 on 2020-02-19 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_accountm'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountm',
            name='AccountType',
            field=models.CharField(default='', max_length=60),
        ),
    ]
