# Generated by Django 3.0.2 on 2020-02-19 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_accountm_accounttype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accountm',
            old_name='AccountBalance',
            new_name='Account_Balance',
        ),
        migrations.RenameField(
            model_name='accountm',
            old_name='AccountCategory',
            new_name='Account_Category',
        ),
        migrations.RenameField(
            model_name='accountm',
            old_name='AccountCredit',
            new_name='Account_Credit',
        ),
        migrations.RenameField(
            model_name='accountm',
            old_name='AccountDescription',
            new_name='Account_Description',
        ),
        migrations.RenameField(
            model_name='accountm',
            old_name='AccountInitBalance',
            new_name='Account_Initial_Balance',
        ),
        migrations.RenameField(
            model_name='accountm',
            old_name='name',
            new_name='Account_Name',
        ),
        migrations.RenameField(
            model_name='accountm',
            old_name='AccountNumber',
            new_name='Account_Number',
        ),
        migrations.RenameField(
            model_name='accountm',
            old_name='AccountSubCategory',
            new_name='Account_Sub_Category',
        ),
        migrations.RenameField(
            model_name='accountm',
            old_name='AccountType',
            new_name='Account_Type',
        ),
        migrations.RenameField(
            model_name='accountm',
            old_name='DateAdded',
            new_name='Date_Added',
        ),
        migrations.RenameField(
            model_name='accountm',
            old_name='UserID',
            new_name='User_ID',
        ),
    ]
