# Generated by Django 3.0.2 on 2020-02-19 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20200218_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountm',
            name='Account_Balance',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='accountm',
            name='Account_Credit',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='accountm',
            name='Account_Initial_Balance',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
